chore: update `publish_to_pub.yaml`

diff --git a/.github/workflows/publish_to_pub.yml b/.github/workflows/publish_to_pub.yml
--- a/.github/workflows/publish_to_pub.yml
+++ b/.github/workflows/publish_to_pub.yml
@@ -1,22 +1,5 @@
 name: "Publish to pub.dev"
 
-## Caller of this workflow should use it as follows:
-## on:
-##   workflow_dispatch:
-##   push:
-##     tags:
-##       - "v[0-9]+.[0-9]+.[0-9]+*"
-
-## jobs:
-##   publish:
-##     uses: ziqq/flutter_ci_workflows/.github/workflows/publish_to_pub.yml@main
-##     with:
-##       PANA_TOTAL: '110'
-##     secrets:
-##       PUB_CREDENTIAL_JSON: ${{ secrets.PUB_CREDENTIAL_JSON }}
-##       PUB_OAUTH_ACCESS_TOKEN: ${{ secrets.PUB_OAUTH_ACCESS_TOKEN }}
-##       PUB_OAUTH_REFRESH_TOKEN: ${{ secrets.PUB_OAUTH_REFRESH_TOKEN }}
-
 env:
   PUBSPEC_PATH: './pubspec.yaml'
   CHANGELOG_PATH: './CHANGELOG.md'
@@ -38,57 +21,67 @@ on:
 jobs:
   check_versions:
     runs-on: ubuntu-latest
+    env:
+      TAG: ''
+      PUBSPEC_VERSION: ''
+      CHANGELOG_VERSION: ''
     steps:
       - name: Checkout
         uses: actions/checkout@v3
 
-      - name: Get tag
+      - name: 🎯 Get tag
+        id: get_tag
         run: |
-          echo "TAG=$(git describe --tags --abbrev=0 --exact-match --match 'v*' HEAD | cut -c 2-)" >> $GITHUB_ENV
+          TAG=$(git describe --tags --abbrev=0 --exact-match --match 'v*' HEAD | cut -c 2-)
+          echo "TAG=$TAG" >> $GITHUB_ENV
+          echo "tag=$TAG" >> $GITHUB_OUTPUT
 
-      - name: Tag is empty
-        if: ${{ env.TAG == ''}}
-        uses: actions/github-script@v6
-        with:
-          script: |
-            core.setFailed('Tag not found!')
+      - name: ❔ Tag is empty
+        if: ${{ steps.get_tag.outputs.tag == '' }}
+        run: |
+          echo "::error::Tag not found!"
+          exit 1
 
-      - name: Echo tag
+      - name: 💬 Echo tag
         run: |
           echo "TAG: ${{ env.TAG }}"
 
-      - name: Get pubspec version
+      - name: 🚂 Get pubspec version
+        id: get_pubspec_version
         run: |
-          echo "PUBSPEC_VERSION=$(cat $PUBSPEC_PATH | grep -o 'version:[^:]*' | cut -f2 -d":" | xargs)" >> $GITHUB_ENV
+          PUBSPEC_VERSION=$(grep '^version:' $PUBSPEC_PATH | cut -f2 -d":" | xargs)
+          echo "PUBSPEC_VERSION=$PUBSPEC_VERSION" >> $GITHUB_ENV
+          echo "pubspec_version=$PUBSPEC_VERSION" >> $GITHUB_OUTPUT
 
-      - name: Pubspec version is empty
-        if: ${{ env.PUBSPEC_VERSION == ''}}
-        uses: actions/github-script@v6
-        with:
-          script: |
-            core.setFailed('Pubspec version not found!')
+      - name: 🔎 Pubspec version is empty
+        if: ${{ steps.get_pubspec_version.outputs.pubspec_version == '' }}
+        run: |
+          echo "::error::Pubspec version not found!"
+          exit 1
 
-      - name: Echo pubspec version
+      - name: 🔎 Echo pubspec version
         run: |
           echo "Pubspec version: ${{ env.PUBSPEC_VERSION }}"
 
-      - name: Get changelog version
+      - name: 🚂 Get changelog version
+        id: get_changelog_version
         run: |
-          echo "CHANGELOG_VERSION=$(cat $CHANGELOG_PATH | grep -o '## [^:]*' -m '1' | cut -c '4-' | xargs)" >> $GITHUB_ENV
+          CHANGELOG_VERSION=$(grep -o '^## [^ ]*' $CHANGELOG_PATH | head -n1 | cut -c 4- | xargs)
+          echo "CHANGELOG_VERSION=$CHANGELOG_VERSION" >> $GITHUB_ENV
+          echo "changelog_version=$CHANGELOG_VERSION" >> $GITHUB_OUTPUT
 
-      - name: Changelog version is empty
-        if: ${{ env.CHANGELOG_VERSION == ''}}
-        uses: actions/github-script@v6
-        with:
-          script: |
-            core.setFailed('Changelog version not found!')
+      - name: 🔎 Changelog version is empty
+        if: ${{ steps.get_changelog_version.outputs.changelog_version == '' }}
+        run: |
+          echo "::error::Changelog version not found!"
+          exit 1
 
-      - name: Echo changelog version
+      - name: 💬 Echo changelog version
         run: |
           echo "Changelog version: ${{ env.CHANGELOG_VERSION }}"
 
-      - name: Compare versions failed
-        if: "!contains(env.PUBSPEC_VERSION, env.TAG) && !contains(env.CHANGELOG_VERSION, env.TAG)"
+      - name: ❌ Compare versions failed
+        if: ${{ steps.get_pubspec_version.outputs.pubspec_version != env.TAG || steps.get_changelog_version.outputs.changelog_version != env.TAG }}
         run: |
           echo "TAG: ${{ env.TAG }}"
           echo "CHANGELOG: ${{ env.CHANGELOG_VERSION }}"
@@ -96,8 +89,9 @@ jobs:
           echo "::error::The versions don't match!"
           exit 1
 
-      - name: Compare versions succes
+      - name: ✅ Compare versions success
         run: |
+          echo "Versions match:"
           echo "TAG: ${{ env.TAG }}"
           echo "CHANGELOG: ${{ env.CHANGELOG_VERSION }}"
           echo "PUBSPEC: ${{ env.PUBSPEC_VERSION }}"
@@ -106,32 +100,36 @@ jobs:
     needs: check_versions
     runs-on: ubuntu-latest
     steps:
-      - name: Set up Repository
+      - name: 👷 Set up Repository
         uses: actions/checkout@v3
 
-      - name: Set up Dart
+      - name: 👷 Set up Dart
         uses: dart-lang/setup-dart@v1.3
 
-      - name: Install Flutter
+      - name: 👷 Install Flutter
         uses: subosito/flutter-action@v1
         with:
           channel: "stable"
 
-      - name: Install dependencies
+      - name: 👷 Install dependencies
         run: flutter pub get
 
-      - name: Install dependencies
+      - name: 👷 Install Pana
         run: |
           dart pub get
           dart pub global activate pana
 
-      - name: Verify pub score
+      - name: 🔎 Verify pub score
         run: |
-          PANA=$(pana . --no-warning); PANA_SCORE=$(echo $PANA | sed -n "s/.*Points: \([0-9]*\)\/\([0-9]*\)./\1\/\2/p")
+          PANA=$(pana . --no-warning)
+          PANA_SCORE=$(echo "$PANA" | grep -o 'Points: [0-9]*/[0-9]*' | grep -o '[0-9]*/[0-9]*')
           echo "score: $PANA_SCORE"
-          IFS='/'; read -a SCORE_ARR <<< "$PANA_SCORE"; SCORE=SCORE_ARR[0]; TOTAL=SCORE_ARR[1]
-          if [ -z "$1" ]; then MINIMUM_SCORE=${{ inputs.PANA_TOTAL }}; else MINIMUM_SCORE=$1; fi
-          if (( $SCORE < $MINIMUM_SCORE )); then echo "Minimum score $MINIMUM_SCORE was not met!"; exit 1; fi
+          IFS='/' read -r SCORE TOTAL <<< "$PANA_SCORE"
+          MINIMUM_SCORE='${{ inputs.PANA_TOTAL }}'
+          if [ "$SCORE" -lt "$MINIMUM_SCORE" ]; then
+            echo "Minimum score $MINIMUM_SCORE was not met!"
+            exit 1
+          fi
 
   package-publishing:
     needs: [ check_versions, pana ]
